#注册地址 后面改为host域名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765  #8765-
spring:
  application:
    name: service-feign

feign.hystrix.enabled: true