#注册地址 后面改为host域名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765  #8765-
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true


#允许显示所有信息，包括/actuator/health，/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"